const subheading=document.createElement('h3');
const text=document.createTextNode('Buy high quality organic fruits online');
subheading.appendChild(text);
const divs=document.querySelectorAll('div');
divs[0].appendChild(subheading);
subheading.style.fontStyle='italic';
const para=document.createElement('p');
const text2=document.createTextNode('Total fruits: 4');
para.appendChild(text2);
divs[1].insertBefore(para,divs[1][1]);
para.setAttribute('id','fruits-total');